In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,r2_score,confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score,train_test_split
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/Titanic-Dataset.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df = df.drop(['PassengerId','Embarked','Cabin','Ticket','Name'],axis=1)

In [6]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [7]:
new_data = pd.get_dummies(df['Sex'])

In [8]:
df = pd.concat([df,new_data],axis=1)

In [9]:
df = df.drop('Sex',axis=1)

In [10]:
df.head()

   Survived  Pclass   Age  SibSp  Parch     Fare  female  male
0         0       3  22.0      1      0   7.2500       0     1
1         1       1  38.0      1      0  71.2833       1     0
2         1       3  26.0      0      0   7.9250       1     0
3         1       1  35.0      1      0  53.1000       1     0
4         0       3  35.0      0      0   8.0500       0     1

In [11]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
SibSp         0
Parch         0
Fare          0
female        0
male          0
dtype: int64

In [12]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [13]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
female      0
male        0
dtype: int64

In [14]:
df.tail()

     Survived  Pclass   Age  SibSp  Parch   Fare  female  male
886         0       2  27.0      0      0  13.00       0     1
887         1       1  19.0      0      0  30.00       1     0
888         0       3  28.0      1      2  23.45       1     0
889         1       1  26.0      0      0  30.00       0     1
890         0       3  32.0      0      0   7.75       0     1

In [26]:
x = df.iloc[:,1:].values
y = df.iloc[:,0].values

In [27]:
KNN = KNeighborsClassifier()
RD = RandomForestClassifier()
DT = DecisionTreeClassifier()
LG = LogisticRegression()

In [28]:
knn = cross_val_score(KNN,x,y,scoring='accuracy',cv=5)
rd = cross_val_score(RD,x,y,scoring='accuracy',cv=5)
dt = cross_val_score(DT,x,y,scoring='accuracy',cv=5)
lg = cross_val_score(LG,x,y,scoring='accuracy',cv=5)

In [29]:
print(f"The accuracy score  for KNN is :{sum(knn)*100/5} \n The accuracy score for RandomForest is: {sum(rd)*100/5} \n The accuracy score for Decision Tree is :{sum(dt)*100/5} \n The accuracy score for LogisticRegression is:{sum(lg)*100/5}" )

The accuracy score  for KNN is :71.16188563178709
 The accuracy score for RandomForest is: 80.58878915322329
 The accuracy score for Decision Tree is :77.44711568639758
 The accuracy score for LogisticRegression is:78.33845960705543

In [30]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [31]:
RD.fit(X_train,y_train)

RandomForestClassifier()

In [32]:
pred = RD.predict(X_test)

In [33]:
accuracy_score(y_test,pred)*100

82.68156424581005