In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [16]:
df = pd.read_csv('hiring (1).csv')

In [17]:
df.head()

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [19]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [26]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean())

In [27]:
df.head()

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [30]:
new = pd.get_dummies(df['experience'])

In [33]:
df = pd.concat([df,new],axis=1)

In [34]:
df.head()

,experience,test_score(out of 10),interview_score(out of 10),salary($),eleven,five,seven,ten,three,two
0,NaN,8.0,9,50000,0,0,0,0,0,0
1,NaN,8.0,6,45000,0,0,0,0,0,0
2,five,6.0,7,60000,0,1,0,0,0,0
3,two,10.0,10,65000,0,0,0,0,0,1
4,seven,9.0,6,70000,0,0,1,0,0,0

In [35]:
df = df.drop(['experience'],axis=1)

In [36]:
df.head()

,test_score(out of 10),interview_score(out of 10),salary($),eleven,five,seven,ten,three,two
0,8.0,9,50000,0,0,0,0,0,0
1,8.0,6,45000,0,0,0,0,0,0
2,6.0,7,60000,0,1,0,0,0,0
3,10.0,10,65000,0,0,0,0,0,1
4,9.0,6,70000,0,0,1,0,0,0

In [39]:
x = df.drop(['salary($)'],axis=1)
x

,test_score(out of 10),interview_score(out of 10),eleven,five,seven,ten,three,two
0,8.000000,9,0,0,0,0,0,0
1,8.000000,6,0,0,0,0,0,0
2,6.000000,7,0,1,0,0,0,0
3,10.000000,10,0,0,0,0,0,1
4,9.000000,6,0,0,1,0,0,0
5,7.000000,10,0,0,0,0,1,0
6,7.857143,7,0,0,0,1,0,0
7,7.000000,8,1,0,0,0,0,0

In [41]:
y = df['salary($)']
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [42]:
model = LinearRegression()

In [43]:
model.fit(x,y)

LinearRegression()

In [50]:
model.predict([[10.000000,10,0,0,0,0,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([65000.])

In [51]:
model.score(x,y)*100

100.0